# -*- coding: utf-8 -*-
"""StockValuationProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJxsi9A6Cpolwedf-sYs4ScSvrGXcsOj

!!!!To run the program, you will have to give Google authentication!!!
To do this smoothly, run all and in one of the cells below, it will be stuck there and redirect you to
the page to get the google credentials. Copy and paste the key where the program asks you to and the 
program will continue to run.
"

# New Section
"""

import requests
import pandas as pd
import json
import gspread_dataframe as gd
import gspread
from oauth2client.client import GoogleCredentials
from bs4 import BeautifulSoup
from google.colab import auth
import re

#call only once a day for treasury rates
treasury_url='https://www.treasury.gov/resource-center/data-chart-center/interest-rates/pages/textview.aspx?data=yield'
treasury_resp=requests.get(treasury_url)
soup=BeautifulSoup(treasury_resp.text,'html.parser')
table=soup.find('table',{'class':'t-chart'})
dailyrows=table.find_all('tr') #dailyrows will be the global variable to call upon in functions

#need shares outstanding (F214), share price (F215), levered beta (F227), risk free rate (F229)
def valuationinputs(ticker):
  #getting values from apis and websites
  apikey='fed528c725804047f6467af3a1da18de'
  quote_url='https://financialmodelingprep.com/api/v3/quote/'+ ticker + '?apikey=' + apikey
  resp_quote=requests.get(quote_url)
  data_quote=resp_quote.json()
  price=float(data_quote[0]['price']) #price
  sharesoutstanding=float(data_quote[0]['sharesOutstanding']) #outstanding
  #beta from other url
  profile_url='https://financialmodelingprep.com/api/v3/profile/'+ ticker + '?apikey=' + apikey
  resp_profile=requests.get(profile_url)
  data_profile=resp_profile.json()
  beta=float(data_profile[0]['beta']) #beta

  #webscrape daily risk free rate (30y treasure yield) from treasury.gov website
  today_rates=dailyrows[-1]
  rates=today_rates.find_all('td')
  thirtyyearrate=float(rates[-1].text)/100 #risk free rate

  #inputing variables into google sheets
  auth.authenticate_user()
  gc = gspread.authorize(GoogleCredentials.get_application_default())

  spreadsheet=gc.open_by_url('https://docs.google.com/spreadsheets/d/1XWMC_cE2l1j66-wYJ1ln4Hftru0Jiz0ODtmhjFA2RDs/edit?usp=sharing')  
  ws=spreadsheet.worksheet('Financial Model')
  ws2=spreadsheet.worksheet('Valuation Assumptions')
  ws.update_acell('F214',sharesoutstanding)
  ws.update_acell('F215',price)
  ws.update_acell('F227',beta)
  ws2.update_acell('B4',thirtyyearrate)

#allows user to mess with valuation assumptions
def custom_revgrowth(growth):
  auth.authenticate_user()
  gc = gspread.authorize(GoogleCredentials.get_application_default())
  spreadsheet=gc.open_by_url('https://docs.google.com/spreadsheets/d/1XWMC_cE2l1j66-wYJ1ln4Hftru0Jiz0ODtmhjFA2RDs/edit?usp=sharing')  
  ws=spreadsheet.worksheet('Valuation Assumptions')
  ws.update_acell('C2',growth)

def custom_riskfree(rate): #tell me which treasury Y rate they choose instead
  auth.authenticate_user()
  gc = gspread.authorize(GoogleCredentials.get_application_default())
  spreadsheet=gc.open_by_url('https://docs.google.com/spreadsheets/d/1XWMC_cE2l1j66-wYJ1ln4Hftru0Jiz0ODtmhjFA2RDs/edit?usp=sharing')  
  ws=spreadsheet.worksheet('Valuation Assumptions')
  today_rates=dailyrows[-1]
  rates=today_rates.find_all('td')
  if rate=='10Y':
    rate=float(rates[-3].text)/100
  elif rate=='20Y':
    rate=float(rates[-2].text)/100
  elif rate=='30Y':
    rate=float(rates[-2].text)/100
  ws.update_acell('C4',rate)   

def custom_marketreturn(rate): #tell me custom rate
  auth.authenticate_user()
  gc = gspread.authorize(GoogleCredentials.get_application_default())
  spreadsheet=gc.open_by_url('https://docs.google.com/spreadsheets/d/1XWMC_cE2l1j66-wYJ1ln4Hftru0Jiz0ODtmhjFA2RDs/edit?usp=sharing')  
  ws=spreadsheet.worksheet('Valuation Assumptions')
  ws.update_acell('C5',rate)

def custom_termgrowth(growth): 
  auth.authenticate_user()
  gc = gspread.authorize(GoogleCredentials.get_application_default())
  spreadsheet=gc.open_by_url('https://docs.google.com/spreadsheets/d/1XWMC_cE2l1j66-wYJ1ln4Hftru0Jiz0ODtmhjFA2RDs/edit?usp=sharing')  
  ws=spreadsheet.worksheet('Valuation Assumptions')
  ws.update_acell('C3',growth)
  
def show_assumptions():
  auth.authenticate_user()
  gc = gspread.authorize(GoogleCredentials.get_application_default())
  spreadsheet=gc.open_by_url('https://docs.google.com/spreadsheets/d/1XWMC_cE2l1j66-wYJ1ln4Hftru0Jiz0ODtmhjFA2RDs/edit?usp=sharing') 
  ws=spreadsheet.worksheet('Financial Model') 
  ws2=spreadsheet.worksheet('Valuation Assumptions')
  #get default assumptions from spreadsheet to show user
  assumptions={"Revenue Growth": ws.acell('G9').value,
               "Risk Free Rate (Treasury Rate)": ws.acell('F229').value,
               "Expected Market Return": ws.acell('J229').value,
               "Terminal FCF Growth": ws.acell('J225').value}
  return assumptions

def show_valuationstats(): #shows a bunch of potentially helpful numbers to the user after our valuation
  auth.authenticate_user()
  gc = gspread.authorize(GoogleCredentials.get_application_default())
  spreadsheet=gc.open_by_url('https://docs.google.com/spreadsheets/d/1XWMC_cE2l1j66-wYJ1ln4Hftru0Jiz0ODtmhjFA2RDs/edit?usp=sharing') 
  ws=spreadsheet.worksheet('Financial Model')
  valuation_stats={"Revenue Growth": ws.acell('G9').value,
                   "Risk Free Rate (Treasury Rate)": ws.acell('F229').value,
                   "Expected Market Return": ws.acell('J229').value,
                   "Terminal FCF Growth": ws.acell('J225').value,
                   "Real Market Cap": ws.acell('F217').value,
                   "Real Stock Price": ws.acell('F215').value,
                   "Real Stock Beta": ws.acell('F227').value,
                   "Model Market Cap": ws.acell('G204').value,
                   "Model Stock Price": ws.acell('F206').value}
  return valuation_stats

def set_empty(): #run this in the beginning everytime to clear out the custom inputs from last time
  auth.authenticate_user()
  gc = gspread.authorize(GoogleCredentials.get_application_default())
  spreadsheet=gc.open_by_url('https://docs.google.com/spreadsheets/d/1XWMC_cE2l1j66-wYJ1ln4Hftru0Jiz0ODtmhjFA2RDs/edit?usp=sharing')  
  ws=spreadsheet.worksheet('Valuation Assumptions')
  ws.update_acell('C2',"empty")
  ws.update_acell('C3',"empty")
  ws.update_acell('C4',"empty")
  ws.update_acell('C5',"empty")

#!!!!
set_empty()

chart=show_assumptions()

def exportFSToSheet(ticker, limit):
  #income statement
  income_url = 'https://financialmodelingprep.com/api/v3/income-statement/' + ticker + '?limit='+limit+'&apikey=fed528c725804047f6467af3a1da18de'
  #balance sheet
  balance_url = 'https://financialmodelingprep.com/api/v3/balance-sheet-statement/' + ticker + '?apikey=fed528c725804047f6467af3a1da18de&limit='+limit
  #cash flow
  cash_url = 'https://financialmodelingprep.com/api/v3/cash-flow-statement/' + ticker + '?apikey=fed528c725804047f6467af3a1da18de&limit='+limit

  resp_income = requests.get(income_url)
  data_income = resp_income.json()
  income_df = pd.DataFrame(data_income)

  resp_balance = requests.get(balance_url)
  data_balance = resp_balance.json()
  balance_df = pd.DataFrame(data_balance)

  resp_cash= requests.get(cash_url)
  data_cash = resp_cash.json()
  cash_df = pd.DataFrame(data_cash)



  auth.authenticate_user()
  gc = gspread.authorize(GoogleCredentials.get_application_default())

  file = gc.open_by_url('https://docs.google.com/spreadsheets/d/1XWMC_cE2l1j66-wYJ1ln4Hftru0Jiz0ODtmhjFA2RDs/edit?usp=sharing') 

  #see if the sheets already exist, if not then create it


  try:
    cash_sheet = file.worksheet("CF(ignore)")
  except gspread.WorksheetNotFound:
    cash_sheet = file.add_worksheet(title="CF(ignore)", rows="100", cols="50")
  try:
    balance_sheet = file.worksheet("BS(ignore)")
  except gspread.WorksheetNotFound:
    balance_sheet = file.add_worksheet(title="BS(ignore)", rows="100", cols="50")
  try:
    income_sheet = file.worksheet("IS(ignore)")
  except gspread.WorksheetNotFound:
    income_sheet = file.add_worksheet(title="IS(ignore)", rows="100", cols="50")

  
  file.values_clear('CF(ignore)!B1:AM1000')
  file.values_clear('BS(ignore)!B1:AM1000')
  file.values_clear('IS(ignore)!B1:AM1000')

  #update the sheets to reflect the df
  gd.set_with_dataframe(cash_sheet, cash_df, col=2)
  gd.set_with_dataframe(balance_sheet, balance_df, col=2)
  gd.set_with_dataframe(income_sheet, income_df, col=2)

def GetPrice():

  auth.authenticate_user()
  gc = gspread.authorize(GoogleCredentials.get_application_default())
  file = gc.open_by_url('https://docs.google.com/spreadsheets/d/1XWMC_cE2l1j66-wYJ1ln4Hftru0Jiz0ODtmhjFA2RDs/edit?usp=sharing') 
  ws=file.worksheet('Financial Model')
  data = ws.get_all_values()
  headers = data.pop(0)
  df = pd.DataFrame(data, columns=headers)
  price = df.loc[204][5]
  price_string = re.search(r"[0-9].*", price).group(0)
  price_float = float(price_string)
  return price_float
def RealPrice(ticker):
  quote = 'https://financialmodelingprep.com/api/v3/quote/'+ticker+'?apikey=fed528c725804047f6467af3a1da18de'
  resp_quote = requests.get(quote)
  data_quote = resp_quote.json()
  quote_df = pd.DataFrame(data_quote)
  Acprice = quote_df.loc[0]["price"]
  return Acprice
def comparison(CaPrice,AcPrice):
  dif = CaPrice - AcPrice
  CaPrice = CaPrice
  AcPrice = AcPrice
  dif = (AcPrice - CaPrice)/CaPrice
  percent = str(dif*100)+"%"
  if dif >= 0.15:
    return ("The current price is overvalued by "+percent+". Consider to decrease your position.")
  if dif >= 0 and dif<0.15:
    return ("The current price is slightly overvalued by "+percent+". Recommend to hold in a bull market.")
  if dif < 0 and dif>-0.15:
    return ("The current price is undervalued by "+percent+". Recommend to hold in a bull market.")
  if dif <= -0.15:
    return ("The current price is largely undervalued by "+percent+". Recommend a buy on this stock.")

def zscorerec():
  auth.authenticate_user()
  gc = gspread.authorize(GoogleCredentials.get_application_default())
  spreadsheet=gc.open_by_url('https://docs.google.com/spreadsheets/d/1XWMC_cE2l1j66-wYJ1ln4Hftru0Jiz0ODtmhjFA2RDs/edit?usp=sharing') 
  ws=spreadsheet.worksheet('Z-Score')
  zscore=float(ws.acell("B8").value)
  if zscore<1.8:
    return ("The Company's Altman's Z-Score is "+str(zscore)+". Proceed with high caution as Company shows high risk of bankruptcy.")
  elif zscore>=1.8 and zscore<3:
    return ("The Company's Altman's Z-Score is "+str(zscore)+". Proceed with some caution as Company shows some risk of bankruptcy.")
  elif zscore>=3:
    return ("The Company's Altman's Z-Score is "+str(zscore)+". Company shows very low risk of bankruptcy and is in a very solid financial position.")

#front end 
#install flask
!pip install flask==0.12.2
!pip install flask-ngrok
!pip install Jinja2
!pip install libsass

!mkdir templates
!mkdir static
!mkdir templates/html
!mkdir static/css
!mkdir static/sass

# Commented out IPython magic to ensure Python compatibility.
# %%writefile static/sass/style.scss
# /* Borrowed and revised from the following CodePen url https://codepen.io/kootoopas/pen/reyqg
#  * Twitter: @kootoopas
#  */
# 
# /* Exo thin font from Google. */
# /*@import url(https://fonts.googleapis.com/css?family=Exo:100);*/
# 
# /* Background data (Original source: https://subtlepatterns.com/grid-me/) */
# 
# 
# $bg-url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAIAAACRXR/mAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAABnSURBVHja7M5RDYAwDEXRDgmvEocnlrQS2SwUFST9uEfBGWs9c97nbGtDcquqiKhOImLs/UpuzVzWEi1atGjRokWLFi1atGjRokWLFi1atGjRokWLFi1af7Ukz8xWp8z8AAAA//8DAJ4LoEAAlL1nAAAAAElFTkSuQmCC";
# $bg-width: 50px;
# $bg-height: 50px;
# 
# /* Animations */
# @-webkit-keyframes bg-scrolling-reverse {
#   100% { background-position: $bg-width $bg-height; }
# }
# @-moz-keyframes    bg-scrolling-reverse {
#   100% { background-position: $bg-width $bg-height; }
# }
# @-o-keyframes      bg-scrolling-reverse {
#   100% { background-position: $bg-width $bg-height; }
# }
# @keyframes         bg-scrolling-reverse {
#   100% { background-position: $bg-width $bg-height; }
# }
# 
# @-webkit-keyframes bg-scrolling {
#   0% { background-position: $bg-width $bg-height; }
# }
# @-moz-keyframes    bg-scrolling {
#   0% { background-position: $bg-width $bg-height; }
# }
# @-o-keyframes      bg-scrolling {
#   0% { background-position: $bg-width $bg-height; }
# }
# @keyframes         bg-scrolling {
#   0% { background-position: $bg-width $bg-height; }
# }
# 
# /* Main styles */
# body {
#   margin-top: 13.5rem;
#   
#   color: #999;
#   text-align: center;
#   /* img size is 50x50 */
#   background: url($bg-url) repeat 0 0;
#   
#   -webkit-animation: bg-scrolling-reverse .92s infinite; /* Safari 4+ */
#   -moz-animation:    bg-scrolling-reverse .92s infinite; /* Fx 5+ */
#   -o-animation:      bg-scrolling-reverse .92s infinite; /* Opera 12+ */
#   animation:         bg-scrolling-reverse .92s infinite; /* IE 10+ */
#   -webkit-animation-timing-function: linear;
#   -moz-animation-timing-function:    linear;
#   -o-animation-timing-function:      linear;
#   animation-timing-function:         linear;
# 
# }
# 
# 
# /*
#   *end of borrowed code
# */
# 
# body {
#   margin: 0;
#   padding: 0;
#   font-family: 'Roboto', sans-serif;
# 
# }
# 
# header {
#   width: 100%;
# }
# 
# h1.index-heading{
#     font-size: 75px;
#     margin-top: 250px;
#     margin-bottom: 20px;
#     color: #6698cb;
# }
# 
# a {
#   text-decoration: none;
#   color: inherit;
# }
# 
# 
# .form {
#   text-align: center;
# }
# 
# #form-search { 
#   margin:0 auto;
#   width:575px;
#   height:45px;
#   border-radius:30px;
#   border:1px solid #dcdcdc;
#   font-size:16px;
#   outline: none;
# 
# }
# 
# .form #form-search {
#   padding: 0 8px;
# }
# 
# #form-search:hover {
#   box-shadow: 1px 1px 8px 1px #dcdcdc;
# }
# 
# #form-search:focus-within{
#   box-shadow: 1px 1px 8px 1px #dcdcdc;
#   outline:none;
# }
# 
# 
# /*nice button design borrowed and revised from https://codepen.io/FelipeMarcos/pen/tfhEg (Felipe Marcos) */
# 
# .btn-gradient {
# 	margin: 5px;
# }
# 
# .btn-gradient {
# 	text-decoration: none;
# 	color: white;
# 	padding: 10px 30px;
# 	display: inline-block;
# 	position: relative;
# 	border: 1px solid rgba(0,0,0,0.21);
# 	border-bottom: 4px solid rgba(0,0,0,0.21);
# 	border-radius: 4px;
# 	text-shadow: 0 1px 0 rgba(0,0,0,0.15);
# }
# 
# .btn-gradient.blue:active 	{background: #608FBF;}
# 
# 
# .btn-gradient.blue {
# 	background: rgba(102,152,203,1);
# 	background: -moz-linear-gradient(top, rgba(102,152,203,1) 0%, rgba(92,138,184,1) 100%);
# 	background: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(102,152,203,1)), color-stop(100%, rgba(92,138,184,1)));
# 	background: -webkit-linear-gradient(top, rgba(102,152,203,1) 0%, rgba(92,138,184,1) 100%);
# 	background: -o-linear-gradient(top, rgba(102,152,203,1) 0%, rgba(92,138,184,1) 100%);
# 	background: -ms-linear-gradient(top, rgba(102,152,203,1) 0%, rgba(92,138,184,1) 100%);
# 	background: linear-gradient(to bottom, rgba(102,152,203,1) 0%, rgba(92,138,184,1) 100%);
# 	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#6698cb', endColorstr='#5c8ab8', GradientType=0 );
# }
# 
# 
# /*nice button design borrowed and revised from https://codepen.io/FelipeMarcos/pen/tfhEg (Felipe Marcos) */
# 
# 
# h1.rec-heading {
#     font-size: 100px;
#     margin-left: 70px;
#     color: #6698cb;
#     text-align: left;
#     margin-top: 30px;
#     margin-bottom: 15px;
# }
# 
# img.stock-plot { 
#     display:block; 
#     margin-left: auto;
#     margin-right: auto;
#     }  
# 
# div.image-container {
#     text-align:center;
# }
# 
# img.sp-plot {
#     display:inline-block;
#     width: 25%;
# }
# 
# img.djia-plot {
#     display:inline-block;
#     width: 25%;
# }
# 
# img.nasdaq-plot {
#     display:inline-block;
#     width: 25%;
# }
# 
# table.input-assumptions {
#   margin-left: auto;
#   margin-right: auto;
#   }
# 
# .input-assumption-field {
#   border-radius:30px;
#   border:1px solid #dcdcdc;
#   outline: none;
#   width: 210px;
# }
# 
# .input-assumption-field:hover {
#   box-shadow: 1px 1px 8px 1px #dcdcdc;
# }
# 
# .input-assumption-field:focus-within{
#   box-shadow: 1px 1px 8px 1px #dcdcdc;
#   outline:none;
# }
# 
# 
# 
# 
# div.rec-container {
# 	width: 95%;
# 	height: 95%;
#   margin: auto;
# 	box-shadow: 0 0 1rem 0 rgba(0, 0, 0, .2);	
# 	border-radius: 5px;
# 	position: relative;
# 	z-index: 1;
# 	background: inherit;
# 	overflow: hidden;
# }
# 
# div.rec-container:before {
# 	content: "";
# 	position: absolute;
# 	background: inherit;
# 	z-index: -1;
# 	top: 0;
# 	left: 0;
# 	right: 0;
# 	bottom: 0;
# 	box-shadow: inset 0 0 2000px rgba(255, 255, 255, .5);
# 	filter: blur(10px);
# 	margin: -20px;
# }
# 
# 
# h2.rec-heading2 {
#     margin-left: 20px;
#     margin-top: 5px;
#     color: #6698cb;
#     text-align: left;
#     margin-left: 70px;
#     margin-right: 70px;
# }
# 
# div.rec-p-container {
#     background-color: #ffffff;
#     width: 55%;
#     margin: 5px;
#     display: inline-block;
#     float: left;
#     margin-left: 70px;
#     box-shadow: 0 0 1rem 0 rgba(0, 0, 0, .2);	
#     border-radius: 5px;
#     margin-right: 70px;
# }
# 
# /* styling red vertical line */
# div.red-line {
#   content: '';
#   width: 2px;
#   height: 100%;
#   position: absolute;
#   top: 0;
#   left: 40px;
#   background-color: rgba(255,0,0,0.6);
# }
# 
# p.rec-variable {
#     margin-left: 20px;
#     margin-top: 5px;
#     color: #6698cb;
#     text-align: left;
#     margin-bottom: 5px;
#     padding-top: 8px;
# }
# 
# p.zscore-variable {
#     margin-left: 20px;
#     margin-top: 0;
#     color: #6698cb;
#     text-align: left;
# }
# 
# p.error {
#     color: red;
# }
# 
# div.stock-plot-container {
#   width:50%;
#   text-align:center;
#   padding:20px;
# }
# 
# img.stock-plot {
#   width: 100%;
#   height: 100%;
#   object-fit: contain;    
# }
# 
# table.input-assumptions {
#     margin-top:5px;
# }
# 
# table.valuation-stats-table p {
#   color: #6698cb;
#   text-align: right;
#   padding-left: 25px;
#   font-size: 23px;
#   padding-right: 25px;
# }
# 
# 
# 
# 
# div.valuation-table-container {
#   display: inline-block;
#   float: right;
#   width: 30%;
#   background-color: #ffffff;
#   margin-right: 100px;
#   box-shadow: 0 0 1rem 0 rgba(0, 0, 0, .2);	
# 	border-radius: 5px;
#   min-width: 250px;
#   margin-top: 5px;
# }
# 
# button.goBack-button {
#     float: right;
# }
# 
# #go-back-button {
#   margin: 40px;
# }
# 
# 
# /*quick scrap up for responsiveness, anything below half a 15 inch laptop */
# @media only screen and (max-width: 1201px) {
#     div.rec-p-container {
#         width: 50%;
#         margin-right: 60px;
#     }
# 
#     div.valuation-table-container {
#         margin-right: 90px;
#     }
# 
#     div.stock-plot-container {
#         width: 60%;
#         margin-bottom: 40px;   
#     }
# 
# }
# 
#

import sass
sass.compile(dirname=('static/sass', 'static/css'), output_style='compressed')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile templates/index.html
# <!DOCTYPE html>
# <html class="home">
#   <head>
#     <title>Homepage</title>
#     <link rel="stylesheet" href="/static/css/style.css">
#   </head>
#   <body>
#     <div class="form">  
#       <h1 class="index-heading">Stock Analysis</h1>
#       {% if error %}
#         <p class=error><strong>Error:</strong> {{ error }}
#       {% endif %}
#       <form action="/get-text" method="POST">
#         <label for="form-search"></label>
#         <input type="text" id="form-search" name="inputticker" placeholder="Search for any stock ticker">
#         <div>
#           <table class="input-assumptions">
#             <tr>
#               <td>
#               {% if data_chart %}
#                 <input class = "input-assumption-field" type="text" name="input-revGrowth" placeholder="{{'Revenue Growth: ex. ' + data_chart['Revenue Growth']}}" >%</input>
#                 <input class = "input-assumption-field" type="text" name="input-riskFree" placeholder="Risk Free Rate: 10Y, 20Y, or 30Y">Y</input>
#                 <input class = "input-assumption-field" type="text" name="input-marketReturn" placeholder="{{'Expected Market Return: ex. ' + data_chart['Expected Market Return']}}">%</input>
#                 <input class = "input-assumption-field" type="text" name="input-termGrowth" placeholder="{{'Terminal FCF Growth: ex. ' + data_chart['Terminal FCF Growth']}}">%</input>
#               {% endif %}
#             </td>
#         </tr>
#      </table>
#      </div>
#       <div class="button">
#         <input class="btn-gradient blue" type="submit" value="Submit" id="search">
#       </div>
#      </form>
#     </div>
#   </body>
# </html>

# Commented out IPython magic to ensure Python compatibility.
# #return page
# %%writefile templates/html/recommendation.html
# <!DOCTYPE html>
# <html class="recommendation">
#   <head>
#     <title>Recommendation</title>
#     <link rel="stylesheet" href="/static/css/style.css">
#   </head>
#   <body>
#   <div class = "rec-container"> 
#     <h1 class="rec-heading">Recommendation</h1>
#     <h2 class="rec-heading2">Judging by the company's financials, we believe the following:</h2>
#     <div class="rec-p-container">
#         <p class="rec-variable">{{ rec }}</p>
#         <p class="zscore-variable">{{ zscore }}</p>
#     </div>
#     <div class="valuation-table-container">
#     <table class="valuation-stats-table">
#       <tr>
#         <td>
#           {% if valuation_stats %}
#                 <p>Model Market Cap: {{valuation_stats['Model Market Cap']}}</p>
#                 <p>Model Stock Price: {{valuation_stats['Model Stock Price']}}</p>
#                 <p>Real Market Cap: {{valuation_stats['Real Market Cap']}}</p>
#                 <p>Real Stock Beta: {{valuation_stats['Real Stock Beta']}}</p>
#                 <p>Real Stock Price: {{valuation_stats['Real Stock Price']}}</p>
#                 <p>Revenue Growth: {{valuation_stats['Revenue Growth']}}</p>
#                 <p>Risk Free Rate (Treasury Rate): {{valuation_stats['Risk Free Rate (Treasury Rate)']}}</p>
#                 <p>Expected Market Return: {{valuation_stats['Expected Market Return']}}</p>
#                 <p>Terminal FCF Growth: {{valuation_stats['Terminal FCF Growth']}}</p>
#               {% endif %}
#             </td>
#         </tr>
#      </table>
#      </div>
#      <div class="stock-plot-container">
#       <a >
#         <img class="stock-plot" src="/plot_stockGraph.png" alt="Stock Graph" onclick="window.open('/stockGraph.html', '_blank');">
#       </a>
#       </div> 
#     <div class="image-container"
#       <a>
#         <img class="sp-plot" src="/plot_SP500.png" alt="S&P500 Graph">
#       </a>
#       <a>
#         <img class="djia-plot" src="/plot_DJIA.png" alt="Dow Jones Industrial Average Graph">
#       </a>
#       <a>
#         <img class="nasdaq-plot" src='/plot_NASDAQ.png' alt="Dow Jones Industrial Average Graph">
#       </a>
#     </div>
#     <button id="go-back-button" onclick="document.location='/'" class="btn-gradient blue" onclick="goBack()">Go Back</button>
#   </div> 
#   </body>
# </html>
# 
#

import requests
import json


def checkticker(ticker):
  apikey='fed528c725804047f6467af3a1da18de'
  list_url='https://financialmodelingprep.com/api/v3/stock/list'+'?apikey=' + apikey
  resp=requests.get(list_url)
  data_tickers=resp.json()
  listoftickers=[]
  for tick in data_tickers:
    listoftickers.append(tick['symbol'])
  if ticker not in listoftickers:
    return False
  else:
    return True


def checkNumeric(number):
 # number = number.replace('%', '')
 if number != '' and number != None:
    try:
      val = int(number)
    except ValueError:
      return False 
  #number = number + '%'
    return True
 else: 
    return True

#######for checkticker to work, this group of code has to happen somewhere before calling checkticker
###from here:
#get a list of tickers we can access


#check ticker's existence in our api  
#ticker=input("Input ticker here: ")
#while checkticker(ticker) !=True:
#  ticker=input('Sorry ticker not found please enter another: ') #something along these lines of a while loop

####to here

" "
#import it and ngrok
import matplotlib
import numpy as np
from flask import Flask, request, render_template, flash
from flask_ngrok import run_with_ngrok
import io
import requests
from flask import Response
import random
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
from io import BytesIO
import requests
from pandas_datareader import data as web
import plotly.graph_objects as go
import plotly.io as pio
import plotly.express as px
import webbrowser


#global var for ticker

#set special var __name__ that holds the name of the current module
app = Flask(__name__) #, template_folder = '/content/templates')
app._static_folder = '/content/static'
app.secret_key = 'fdajfdkajfkldajfkldsjlffdsa3353253532'
#Scss(app, static_dir='/content/static/css', asset_dir='/content/static/sass')

#bootstrap = Bootstrap(app)


##############################################
#NOT THREAD SAFE WORKAROUND -- COULD CAUSE ISSUES
#planning to use sessions as a thread safe solution long term

class DataStore():
  ticker = None

data = DataStore()
##############################################
run_with_ngrok(app) 

#special decorator -- turns regular python function into a flask view function 
@app.route('/')
def home():
    data_chart = chart
    return render_template("index.html", data_chart=data_chart)


@app.route('/get-text', methods=['GET', 'POST'])
def mainfunction():
  import requests
  import pandas as pd
  import json
  import gspread_dataframe as gd
  import gspread
  from oauth2client.client import GoogleCredentials
  from bs4 import BeautifulSoup
  from google.colab import auth
  data_chart = chart
  ticker = request.form.get("inputticker")
  ticker = ticker.upper()

  set_empty()
  #check to see if custom_revgrowth, custom_riskfree, custom_termgrowth available
  revGrowth = request.form.get("input-revGrowth")
  riskFree = request.form.get("input-riskFree")
  termGrowth = request.form.get("input-termGrowth")
  marketReturn = request.form.get("input-marketReturn")
  
  #this is for error handling if the ticker is incorrect
  
  error = None
  if request.method == 'POST':
    #the checkNumeric function currently does not work if there isn't any input 
    if checkticker(ticker) != True or checkNumeric(revGrowth) != True or checkNumeric(termGrowth) != True or checkNumeric(marketReturn) != True or checkNumeric(riskFree) != True: #riskFree does not work 
      error = 'Invalid Input'
    else:
      goodticker=ticker
      data.ticker = goodticker
      valuationinputs(goodticker)
      exportFSToSheet(goodticker, '10')
      CaPrice = GetPrice()
      AcPrice = RealPrice(goodticker)
      recommendation = comparison(CaPrice,AcPrice)
      zscore = zscorerec()

      #utilize custom input methods
      if revGrowth != '' and revGrowth != None:
        custom_revgrowth(revGrowth + '%')
      else:
        custom_revgrowth(revGrowth)


      if riskFree != '' and riskFree != None:
        custom_riskfree(riskFree + 'Y')
      else:
        custom_riskfree(riskFree)


      if termGrowth != '' and termGrowth != None:
        custom_termgrowth(termGrowth+ '%')
      else:
        custom_termgrowth(termGrowth)#+ '%')


      if marketReturn != '' and marketReturn != None:
        custom_marketreturn(marketReturn + '%')
      else:
        custom_marketreturn(marketReturn)# + '%')

      valuation_stats = show_valuationstats()

      return render_template('/html/recommendation.html', rec=recommendation, zscore=zscore, valuation_stats=valuation_stats)
    return render_template('index.html', error=error, data_chart=data_chart)

  """
  #session['ticker'] = 'this_ticker'

  goodticker = ticker
  data.ticker = goodticker

  valuationinputs(goodticker)

  #after this part, show user what parts they can chose to change/customize
  #show them our current assumptions (revenue growth, risk free rate (30Y), terminal growth rate)
  #they can change them if they wish 
  #if they change them, must call the custom_revgrowth, custom_riskfree, custom_termgrowth


  exportFSToSheet(goodticker, '10')
  CaPrice = GetPrice()
  AcPrice = RealPrice(goodticker)
  recommendation = comparison(CaPrice,AcPrice)
  return render_template('/html/recommendation.html', rec=recommendation)
"""
@app.route('/plot_stockGraph.png')
def plot_stockGraph():
  apikey='fed528c725804047f6467af3a1da18de'
  #ticker = session.get('ticker', None)
  ticker = data.ticker
  list_url='https://financialmodelingprep.com/api/v3/historical-price-full/' + ticker + '?apikey=' + apikey 
  resp=requests.get(list_url)
  historical_prices = resp.json()
  historical_prices = historical_prices['historical'][:600]
  historical_prices_df = pd.DataFrame.from_dict(historical_prices)
  historical_prices_df = historical_prices_df.set_index('date')
  historical_prices_df = historical_prices_df.iloc[::-1]
  CaPrice = GetPrice()
  #calculate MA5 and MA20 in the graph
  MA5 = historical_prices_df.close.rolling(5).mean()
  MA20 = historical_prices_df.close.rolling(20).mean()
  fig = Figure(dpi=600)
  axis = fig.add_subplot(1, 1, 1)
  # make k-line
  # candlestick chart is made based on https://towardsdatascience.com/using-python-to-visualize-stock-data-to-candlestick-charts-e1a5b08c8e9c
  trace1 = {
    'x': historical_prices_df.index,
    'open': historical_prices_df.open,
    'close': historical_prices_df.close,
    'high': historical_prices_df.high,
    'low': historical_prices_df.low,
    'type': 'candlestick',
    'name': ticker,
    'showlegend': True}
  # make MA5
  trace2 = {
    'x': historical_prices_df.index,
    'y': MA5,
    'type': 'scatter',
    'mode': 'lines',
    'line': {
        'width': 1,
        'color': 'blue'
            },
    'name': 'Moving Average of 5 periods'
}
  # make MA20
  trace3 = {
    'x': historical_prices_df.index,
    'y': MA20,
    'type': 'scatter',
    'mode': 'lines',
    'line': {
        'width': 1,
        'color': 'yellow'
    },
    'name': 'Moving Average of 20 periods'
}
  data11=[trace1,trace2,trace3]
  # draw annotation about the target price
  layout = go.Layout({
    'title': {
        'text': ticker+' Moving Averages',
        'font': {
            'size': 15
        }
    },
      'annotations':[
    {
      'x': historical_prices_df.iloc[-1].name,
      'y': CaPrice,
      'xref': 'x',
      'yref': 'y',
      'text': 'target price'+str(CaPrice),
      'font': {'color': 'magenta'},
      'showarrow': True,
      'arrowcolor':'magenta',
      'ax': 80,
      'arrowsize':8,
      'startarrowhead':8,
      'xshift':10
    }
  ]

})
  #use plotly to draw the graph
  candlestick = go.Figure(data11,layout)
  #save the html file
  candlestick.write_html("templates/html/"+ticker+"stockGraph.html")
  xs = historical_prices_df.index
  ys = historical_prices_df['close']
  axis.plot(xs, ys)
  axis.tick_params(labelrotation=60)
  axis.set_xticks(np.arange(0, len(historical_prices_df.index)+1, 80))
  axis.title.set_text(ticker) 
  output = io.BytesIO()
  FigureCanvas(fig).print_png(output)
  return Response(output.getvalue(), mimetype='image/png')

@app.route('/stockGraph.html')
def stockGraph():
  ticker = data.ticker
  return render_template("html/"+ticker+"stockGraph.html")

@app.route('/plot_SP500.png')
def plot_SP500():
  fig = Figure(dpi=600)
  axis = fig.add_subplot(1, 1, 1)
  apikey='fed528c725804047f6467af3a1da18de'
  list_url='https://financialmodelingprep.com/api/v3/historical-price-full/%5EGSPC?apikey=' + apikey 
  resp=requests.get(list_url)
  historical_prices = resp.json()
  
  historical_prices = historical_prices['historical'][:600]
  historical_prices_df = pd.DataFrame.from_dict(historical_prices)

  historical_prices_df = historical_prices_df.set_index('date')
  historical_prices_df = historical_prices_df.iloc[::-1]
  historical_prices_df = historical_prices_df.drop(columns=['open', 'high', 'low', 'volume', 'adjClose', 'unadjustedVolume', 'change', 'changePercent', 'label','vwap','changeOverTime'])


  xs = historical_prices_df.index
  ys = historical_prices_df['close']
  axis.plot(xs, ys)
  axis.tick_params(labelrotation=60)
  axis.set_xticks(np.arange(0, len(historical_prices_df.index)+1, 80))
  axis.title.set_text("S&P 500") 
  output = io.BytesIO()
  FigureCanvas(fig).print_png(output)
  return Response(output.getvalue(), mimetype='image/png')


@app.route('/plot_DJIA.png')
def plot_DJIA():
  fig = Figure(dpi=600)
  axis = fig.add_subplot(1, 1, 1)
  apikey='fed528c725804047f6467af3a1da18de'
  list_url='https://financialmodelingprep.com/api/v3/historical-price-full/^DJI?apikey=' + apikey 
  resp=requests.get(list_url)
  historical_prices = resp.json()
  
  historical_prices = historical_prices['historical'][:600]
  historical_prices_df = pd.DataFrame.from_dict(historical_prices)

  historical_prices_df = historical_prices_df.set_index('date')
  historical_prices_df = historical_prices_df.iloc[::-1]
  historical_prices_df = historical_prices_df.drop(columns=['open', 'high', 'low', 'volume', 'adjClose', 'unadjustedVolume', 'change', 'changePercent', 'label','vwap','changeOverTime'])


  xs = historical_prices_df.index
  ys = historical_prices_df['close']
  axis.plot(xs, ys)
  axis.tick_params(labelrotation=60)
  axis.set_xticks(np.arange(0, len(historical_prices_df.index)+1, 80))
  axis.title.set_text("DJIA") 
  output = io.BytesIO()
  FigureCanvas(fig).print_png(output)
  return Response(output.getvalue(), mimetype='image/png')



@app.route('/plot_NASDAQ.png')
def plot_NASDAQ():
  fig = Figure(dpi=600)
  axis = fig.add_subplot(1, 1, 1)
  apikey='fed528c725804047f6467af3a1da18de'
  list_url='https://financialmodelingprep.com/api/v3/historical-price-full/^IXIC?apikey=' + apikey 
  resp=requests.get(list_url)
  historical_prices = resp.json()
  
  historical_prices = historical_prices['historical'][:600]
  historical_prices_df = pd.DataFrame.from_dict(historical_prices)

  historical_prices_df = historical_prices_df.set_index('date')
  historical_prices_df = historical_prices_df.iloc[::-1]
  historical_prices_df = historical_prices_df.drop(columns=['open', 'high', 'low', 'volume', 'adjClose', 'unadjustedVolume', 'change', 'changePercent', 'label','vwap','changeOverTime'])


  xs = historical_prices_df.index
  ys = historical_prices_df['close']
  axis.plot(xs, ys)
  axis.tick_params(labelrotation=60)
  axis.set_xticks(np.arange(0, len(historical_prices_df.index)+1, 80))
  axis.title.set_text("NASDAQ") 
  output = io.BytesIO()
  FigureCanvas(fig).print_png(output)
  return Response(output.getvalue(), mimetype='image/png')

if __name__ == '__main__':
    app.run()